### ISSUE TITLE
PowerPointViewer.exe 404: Not Found

### ISSUE THREAD

**Issue by newmentos** [a13/ttf-vista-fonts#1]
> wget http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe
--2018-07-19 12:19:18--  http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe
Распознаётся download.microsoft.com (download.microsoft.com)... 2.23.109.19, 2a02:26f0:9c00:1a2::e59, 2a02:26f0:9c00:192::e59
Подключение к download.microsoft.com (download.microsoft.com)|2.23.109.19|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа... 404 Not Found
2018-07-19 12:19:18 ОШИБКА 404: Not Found.

**Comment by a13** [comment]
sorry, It looks like MS removed PPV from downloads, at least I couldn't find it, you can try to find a copy somewhere else and put it in a build directory

**Comment by a13** [comment]
@newmentos Hi! I replaced the URL with the archive.org version, looks like it works ok!
